compilar:
	gcc main.c -o main -lpthread -lrt
	gcc jugador/main.c -o jugador/main -lpthread -lrt

server:
	gcc main.c -o main -lpthread -lrt

jugador:
	gcc jugador/main.c -o jugador/main -lpthread -lrt
